fragment PageParts on Page {
  __typename
  ... on PageIndex {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    homeSlider {
      __typename
      slideType
      quoteText
      author
      audioLabel
      audioFile
    }
    latestBanner
    latestActionText
    latestActionImage
    latestAlt
    latestActionVideo
    latestActionButton
    latestActionLink
    teamImage
    teamAlt
    teamTitle
    teamText
  }
  ... on PageAbout {
    title
    bannerTitle
    aboutImage
    alt
    statistics {
      __typename
      statNum
      statText
    }
    thanksList {
      __typename
      name
      logo
      link
    }
  }
  ... on PageRightsrecorder {
    title
    bannerTitle
    bannerText
    introText
    iconBlocksList {
      __typename
      title
      text
      image
      alt
    }
    yellowBannerTitle
    yellowBannerText
    yellowBannerLink
  }
  ... on PageAdvocateportal {
    title
    bannerTitle
    bannerText
    scheduleLink
    demoLink
    iconBlocksList {
      __typename
      title
      text
      image
      alt
    }
    yellowBannerTitle
    yellowBannerText
    yellowBannerLink
  }
  ... on PageDatapage {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
      }
    }
    orangeBannerTitle
    orangeBannerText
    orangeBannerButton
    orangeBannerLink
  }
  ... on PageVoucherholders {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    keysHeadline
    keyImage1
    keyImage2
    keyImage3
    keyImage4
    statistics {
      __typename
      statNum
      statText
    }
    quote
    quoteAuthor
    authorTitle
    authorImg
    linksList {
      __typename
      title
      text
      image
      org
      button
      buttonText
      buttonLink
    }
  }
  ... on PageCommunityorganizers {
    title
    bannerTitle
    bannerSubtitle
    bannerText
    bannerLink
    topImage
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    orangeBannerTitle
    orangeBannerButton
    orangeBannerLink
  }
  ... on PageHousingspecialists {
    title
    bannerTitle
    bannerSubtitle
    topImage
    topImageAlt
    demoLink
    signUpLink
    quote
    quoteAuthor
    quoteTitle
    quoteImg
    titleAboveStats
    textAboveStats
    statistics {
      __typename
      statNum
      statText
    }
    featuredPartnerText
    linksList {
      __typename
      title
      content
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    partnersList {
      __typename
      name
      logo
      link
    }
  }
  ... on PageFunding {
    title
    bannerTitle
    bannerTextRich
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    statsTitle
    statistics {
      __typename
      statNum
      statText
    }
    statsText
    fundersList {
      __typename
      name
      logo
      link
    }
    orangeBannerTitle
    annualReports {
      __typename
      year
      pdf
    }
  }
  ... on PagePolicy {
    title
    effective
    revised
    body
  }
  ... on PagePress {
    title
    bannerTitle
    bannerText
    kit1
    kit1PDF
    kit2
    kit2Text
    kit2Link
    orangeBannerTitle
    orangeBannerText
  }
  ... on PageInvolved {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    orangeBannerTitle
    orangeBannerText
    orangeBannerLink
  }
}

fragment BioParts on Bio {
  __typename
  name
  title
  tags
  image
  order
}

fragment FaqParts on Faq {
  __typename
  question
  answer
  tags
  order
}

fragment ArticleParts on Article {
  __typename
  title
  author
  excerpt
  image
  alt
  tags
  keywords
  body
}

fragment ReportParts on Report {
  __typename
  reportTitle
  featured
  year
  reportSummaryTop
  reportSummary
  keywords
  reportPDF
}

fragment PressParts on Press {
  __typename
  title
  pubdate
  image
  link
  tags
}

fragment ReleaseParts on Release {
  __typename
  title
  excerpt
  keywords
  year
  pdf
}
