fragment PageParts on Page {
  ... on PageIndex {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      alt
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    latestBanner
    latestActionText
    latestActionImage
    latestActionVideo
    latestActionButton
    latestActionLink
  }
  ... on PageAbout {
    title
    bannerTitle
  }
  ... on PageRightsrecorder {
    title
    bannerTitle
    bannerText
    iconBlocksList {
      __typename
      title
      text
      image
    }
  }
  ... on PageAdvocateportal {
    title
    bannerTitle
    bannerText
    iconBlocksList {
      __typename
      title
      text
      image
      button
      buttonText
    }
    yellowBannerTitle
    yellowBannerText
  }
  ... on PageDatapage {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      button
      buttonList {
        __typename
        buttonText
      }
    }
    orangeBannerTitle
    orangeBannerText
  }
  ... on PageVoucherholders {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    keyImage1
    keyImage2
    keyImage3
    keyImage4
    quote
    quoteAuthor
    authorTitle
    linksList {
      __typename
      title
      text
      image
      button
      buttonText
      buttonLink
    }
  }
  ... on PageCommunityorganizers {
    title
    bannerTitle
    bannerSubtitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    orangeBannerTitle
  }
  ... on PageHousingspecialists {
    title
    bannerTitle
    bannerSubtitle
    quote
    quoteAuthor
    quoteTitle
    quoteImg
    linksList {
      __typename
      title
      content
      image
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    partnersList {
      __typename
      name
      logo
      link
    }
  }
  ... on PageFunding {
    title
    bannerTitle
    bannerText
    blocksList {
      __typename
      title
      text
      image
      button
      buttonList {
        __typename
        buttonText
        buttonLink
      }
    }
    fundersList {
      __typename
      name
      logo
      link
    }
    orangeBannerTitle
  }
}

fragment BioParts on Bio {
  name
  title
  tags
  image
  order
}

fragment FaqParts on Faq {
  question
  answer
  tags
  order
}

fragment ArticleParts on Article {
  title
  author
  excerpt
  image
  tags
  keywords
  body
}
