# only allow authenticated "advocates" to report endpoints
[[redirects]]
  from = "/start/secure/advocate/report/*"
  to = "/start/secure/advocate/report/:splat"
  force = true
  status = 200
  conditions = {Role = ["advocate"]}

# redirect anyone not logged in to login page
[[redirects]]
  from = "/start/secure/advocate/report/*"
  to = "/start/secure/advocate/"
  status = 302
  force = true

# quick link for advocate login
[[redirects]]
  from = "/advocate-login"
  to = "/start/secure/advocate/check"
  status = 302
  force = true

[[redirects]]
  from = "https://unlocknyc.org/*"
  to = "https://weunlock.nyc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/report"
  to = "/start"
  status = 301
  force = true

[[redirects]]
  from = "/record"
  to = "/start"
  status = 301
  force = true

# URL mapping from pre-2023 site, reports
[[redirects]]
   from = "/serial-discriminators"
   to = "/reports/serial-discriminators/"
   status = 301
   force = true

# URL mapping from pre-2023 site, reports
[[redirects]]
   from = "/soi-report"
   to = "/reports/illusion-of-choice/"
   status = 301
   force = true

# URL mapping from menu tabs
[[redirects]]
    from = "/tools"
    to = "/rights-recorder/"
    status = 301
    force = true

# URL mapping from menu tabs
[[redirects]]
    from = "/partners"
    to = "/community-organizers/"
    status = 301
    force = true

[[headers]]
  for = "/*"
  [headers.values]
   Access-Control-Allow-Origin = "*"

[[redirects]]
    from = '/api/*'
    to = '/.netlify/functions/api/:splat'
    status = 200

[functions]
    node_bundler = 'esbuild'